version: '3'

services:
  api:
    build:
      context: ./API
    ports:
      - "5001:5001"
    volumes:
      - ./config.json:/app/config.json

  videolibmanager:
    build:
      context: ./VideoLibManager
    ports:
      - "5002:5002"
    volumes:
      - ./config.json:/app/config.json
