version: '3'

services:
  api:
    build:
      context: ./API
    image: api
    ports:
      - "5001:5001"
    volumes:
      - ./API/.:/app

  digitalmovies:
    build:
      context: ./DigitalMovies
    image: digitalmovies
    ports:
      - "5002:5002"
    volumes:
      - ./DigitalMovies/.:/app
