version: '3'

services:
  api:
    build:
      context: ./API
    image: api
    ports:
      - "5001:5001"
    volumes:
      - ./API/.:/app

  videolibmanager:
    build:
      context: ./VideoLibManager
    image: videolibmanager
    ports:
      - "5002:5002"
    volumes:
      - ./VideoLibManager/.:/app
